# this is a very minimal config file in YAML format
# it will be processed by Hydra at runtime

num_rounds: 10 # number of FL rounds in the experiment
num_clients: 100 # number of total clients available
batch_size: 30 # batch size to use by clients during training
num_classes: 10 # number of classes in our dataset (for now cifar10 dataset)
num_clients_per_round_fit: 5 # number of clients to involve in each fit round
num_clients_per_round_eval: 5 # number of clients to involve in each evaluate round
config_fit: # a config that each client will receive
  lr: 0.01 # learning rate to use by the clients
  momentum: 0.9 # momentum used by SGD optimiser on the client side
  local_epochs: 1 # number of training epochs each clients does in a fit() round